package router

import (
	"github.com/kubepilot/kubepilot/internal/authz"
	"github.com/kubepilot/kubepilot/internal/service/access"
	"gorm.io/gorm"
)

// SetupAuthorizer builds the fail-closed policy registry and authorizer.
// Extra registrars (e.g. feature modules) may append policies before the authorizer is created.
func SetupAuthorizer(db *gorm.DB, extra ...func(*authz.Registry) error) (*authz.Registry, *authz.Authorizer) {
	registry := authz.NewRegistry()
	registerAPIPolicies(registry)
	for _, fn := range extra {
		if fn == nil {
			continue
		}
		if err := fn(registry); err != nil {
			panic(err)
		}
	}
	grants := authz.NewAccessServiceResolver(access.NewService(db))
	authorizer := authz.NewAuthorizer(registry, grants, authz.PathScopeResolver{})
	return registry, authorizer
}

func registerAPIPolicies(registry *authz.Registry) {
	registry.MustRegister("GET", "/api/v1/profile", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("PUT", "/api/v1/profile/password", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("GET", "/api/v1/2fa/status", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("POST", "/api/v1/2fa/setup", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("POST", "/api/v1/2fa/verify-enable", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("POST", "/api/v1/2fa/disable", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("GET", "/api/v1/system/users", authz.Policy{Resource: "users", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/system/users", authz.Policy{Resource: "users", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/users/:id", authz.Policy{Resource: "users", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/users/:id", authz.Policy{Resource: "users", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/system/users/:id", authz.Policy{Resource: "users", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/system/users/:id/reset-password", authz.Policy{Resource: "users", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/users/:id/clusters", authz.Policy{Resource: "cluster_access", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/users/:id/clusters", authz.Policy{Resource: "cluster_access", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/users/:id/effective-cluster-permissions", authz.Policy{Resource: "cluster_access", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/users/:id/effective-access", authz.Policy{Resource: "cluster_access", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/user-groups", authz.Policy{Resource: "user_groups", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/system/user-groups", authz.Policy{Resource: "user_groups", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/user-groups/:id", authz.Policy{Resource: "user_groups", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/user-groups/:id", authz.Policy{Resource: "user_groups", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/system/user-groups/:id", authz.Policy{Resource: "user_groups", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/user-groups/:id/members", authz.Policy{Resource: "user_groups", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/user-groups/:id/members", authz.Policy{Resource: "user_groups", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/user-groups/:id/clusters", authz.Policy{Resource: "user_groups", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/user-groups/:id/clusters", authz.Policy{Resource: "user_groups", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/roles", authz.Policy{Resource: "roles", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/system/roles", authz.Policy{Resource: "roles", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/roles/:id", authz.Policy{Resource: "roles", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/system/roles/:id", authz.Policy{Resource: "roles", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/system/roles/:id", authz.Policy{Resource: "roles", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/resources", authz.Policy{Resource: "roles", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/actions", authz.Policy{Resource: "roles", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/role-templates", authz.Policy{Resource: "roles", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/audit-logs", authz.Policy{Resource: "audit_logs", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/system/login-logs", authz.Policy{Resource: "login_logs", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/alerts/rules", authz.Policy{Resource: "alerts", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/alerts/rules", authz.Policy{Resource: "alerts", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/alerts/rules/:id", authz.Policy{Resource: "alerts", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/alerts/rules/:id", authz.Policy{Resource: "alerts", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/alerts/history", authz.Policy{Resource: "alerts", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/alerts/channels", authz.Policy{Resource: "alerts", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/alerts/channels", authz.Policy{Resource: "alerts", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/alerts/channels/:id", authz.Policy{Resource: "alerts", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/alerts/channels/:id", authz.Policy{Resource: "alerts", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/clusters", authz.Policy{Resource: "clusters", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/clusters", authz.Policy{Resource: "clusters", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/clusters/:id", authz.Policy{Resource: "clusters", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id", authz.Policy{Resource: "clusters", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id", authz.Policy{Resource: "clusters", Action: "delete", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/health", authz.Policy{Resource: "clusters", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/info", authz.Policy{Resource: "clusters", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/namespaces", authz.Policy{Resource: "namespaces", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("GET", "/api/v1/clusters/:id/nodes", authz.Policy{Resource: "nodes", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/deployments", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/deployments", authz.Policy{Resource: "deployments", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/deployments/enterprise", authz.Policy{Resource: "deployments", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/deployments/:ns/:name", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/deployments/:ns/:name", authz.Policy{Resource: "deployments", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/services", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/history", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/rollback", authz.Policy{Resource: "deployments", Action: "execute", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/scale", authz.Policy{Resource: "deployments", Action: "execute", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/deployments/:ns/:name", authz.Policy{Resource: "deployments", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/affinity", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/deployments/:ns/:name/affinity", authz.Policy{Resource: "deployments", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/pods", authz.Policy{Resource: "pods", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name/logs", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name/containers", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/pods/:ns/:name", authz.Policy{Resource: "pods", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/pods/:ns/:name", authz.Policy{Resource: "pods", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name/files", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name/files/read", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/pods/:ns/:name/files/write", authz.Policy{Resource: "pods", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/pods/:ns/:name/files", authz.Policy{Resource: "pods", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pods/:ns/:name/files/download", authz.Policy{Resource: "pods", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/services", authz.Policy{Resource: "services", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/services", authz.Policy{Resource: "services", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/services/:ns/:name", authz.Policy{Resource: "services", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/services/:ns/:name", authz.Policy{Resource: "services", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/services/:ns/:name", authz.Policy{Resource: "services", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/nodes", authz.Policy{Resource: "nodes", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/nodes/:name", authz.Policy{Resource: "nodes", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/nodes/:name", authz.Policy{Resource: "nodes", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/namespaces", authz.Policy{Resource: "namespaces", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/namespaces/names", authz.Policy{Resource: "namespaces", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/namespaces", authz.Policy{Resource: "namespaces", Action: "create", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/namespaces/:name", authz.Policy{Resource: "namespaces", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/namespaces/:name", authz.Policy{Resource: "namespaces", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/namespaces/:name", authz.Policy{Resource: "namespaces", Action: "delete", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/namespaces/:name/quotas", authz.Policy{Resource: "namespaces", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/namespaces/:name/quotas", authz.Policy{Resource: "namespaces", Action: "create", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/namespaces/:name/quotas", authz.Policy{Resource: "namespaces", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/namespaces/:name/quotas", authz.Policy{Resource: "namespaces", Action: "delete", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/namespaces/clone", authz.Policy{Resource: "namespaces", Action: "execute", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/events", authz.Policy{Resource: "events", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/cluster-events", authz.Policy{Resource: "events", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/configmaps", authz.Policy{Resource: "configmaps", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/configmaps", authz.Policy{Resource: "configmaps", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/configmaps/:ns/:name", authz.Policy{Resource: "configmaps", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/configmaps/:ns/:name", authz.Policy{Resource: "configmaps", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/configmaps/:ns/:name", authz.Policy{Resource: "configmaps", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/secrets", authz.Policy{Resource: "secrets", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/secrets", authz.Policy{Resource: "secrets", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/secrets/:ns/:name", authz.Policy{Resource: "secrets", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/secrets/:ns/:name", authz.Policy{Resource: "secrets", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/secrets/:ns/:name", authz.Policy{Resource: "secrets", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/ingresses", authz.Policy{Resource: "ingresses", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/ingresses", authz.Policy{Resource: "ingresses", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/ingresses/:ns/:name", authz.Policy{Resource: "ingresses", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/ingresses/:ns/:name", authz.Policy{Resource: "ingresses", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/ingresses/:ns/:name", authz.Policy{Resource: "ingresses", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pvcs", authz.Policy{Resource: "pvcs", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/pvcs", authz.Policy{Resource: "pvcs", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pvcs/:ns/:name", authz.Policy{Resource: "pvcs", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/pvcs/:ns/:name", authz.Policy{Resource: "pvcs", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/pvcs/:ns/:name", authz.Policy{Resource: "pvcs", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/networkpolicies", authz.Policy{Resource: "networkpolicies", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/networkpolicies", authz.Policy{Resource: "networkpolicies", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/networkpolicies/:ns/:name", authz.Policy{Resource: "networkpolicies", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/networkpolicies/:ns/:name", authz.Policy{Resource: "networkpolicies", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/statefulsets", authz.Policy{Resource: "statefulsets", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/statefulsets", authz.Policy{Resource: "statefulsets", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/statefulsets/:ns/:name", authz.Policy{Resource: "statefulsets", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/statefulsets/:ns/:name", authz.Policy{Resource: "statefulsets", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/statefulsets/:ns/:name", authz.Policy{Resource: "statefulsets", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/daemonsets", authz.Policy{Resource: "daemonsets", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/daemonsets", authz.Policy{Resource: "daemonsets", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/daemonsets/:ns/:name", authz.Policy{Resource: "daemonsets", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/daemonsets/:ns/:name", authz.Policy{Resource: "daemonsets", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/daemonsets/:ns/:name", authz.Policy{Resource: "daemonsets", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/jobs", authz.Policy{Resource: "jobs", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/jobs", authz.Policy{Resource: "jobs", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/jobs/:ns/:name", authz.Policy{Resource: "jobs", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/jobs/:ns/:name", authz.Policy{Resource: "jobs", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/cronjobs", authz.Policy{Resource: "cronjobs", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/cronjobs", authz.Policy{Resource: "cronjobs", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/cronjobs/:ns/:name", authz.Policy{Resource: "cronjobs", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/cronjobs/:ns/:name", authz.Policy{Resource: "cronjobs", Action: "edit", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/cronjobs/:ns/:name", authz.Policy{Resource: "cronjobs", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/replicasets", authz.Policy{Resource: "replicasets", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/replicasets/:ns/:name", authz.Policy{Resource: "replicasets", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/replicasets/:ns/:name/scale", authz.Policy{Resource: "replicasets", Action: "execute", Scope: authz.ScopeNamespace})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/replicasets/:ns/:name", authz.Policy{Resource: "replicasets", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/hpas", authz.Policy{Resource: "hpas", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/hpas", authz.Policy{Resource: "hpas", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/hpas/:ns/:name", authz.Policy{Resource: "hpas", Action: "delete", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pvs", authz.Policy{Resource: "pvs", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/pvs", authz.Policy{Resource: "pvs", Action: "create", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/pvs/:name", authz.Policy{Resource: "pvs", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/pvs/:name", authz.Policy{Resource: "pvs", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/pvs/:name", authz.Policy{Resource: "pvs", Action: "delete", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/storageclasses", authz.Policy{Resource: "storageclasses", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/storageclasses", authz.Policy{Resource: "storageclasses", Action: "create", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/storageclasses/:name", authz.Policy{Resource: "storageclasses", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/storageclasses/:name", authz.Policy{Resource: "storageclasses", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/storageclasses/:name", authz.Policy{Resource: "storageclasses", Action: "delete", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/metrics/pods", authz.Policy{Resource: "metrics", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/metrics/deployments", authz.Policy{Resource: "metrics", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/metrics/nodes", authz.Policy{Resource: "metrics", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/metrics/overview", authz.Policy{Resource: "metrics", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/crds", authz.Policy{Resource: "crds", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/crds/:group/:version/:resource", authz.Policy{Resource: "custom_resources", Action: "view", Scope: authz.ScopeNamespaceList, AllowFilteredNamespaceList: true})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/crds/:group/:version/:resource", authz.Policy{Resource: "custom_resources", Action: "create", Scope: authz.ScopeNamespaceList})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/crds/:group/:version/:resource/:name", authz.Policy{Resource: "custom_resources", Action: "view", Scope: authz.ScopeHandler})
	registry.MustRegister("PUT", "/api/v1/clusters/:id/workloads/crds/:group/:version/:resource/:name", authz.Policy{Resource: "custom_resources", Action: "edit", Scope: authz.ScopeHandler})
	registry.MustRegister("DELETE", "/api/v1/clusters/:id/workloads/crds/:group/:version/:resource/:name", authz.Policy{Resource: "custom_resources", Action: "delete", Scope: authz.ScopeHandler})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/yaml/:type/:ns/:name", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeHandler})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/yaml/apply", authz.Policy{Resource: "deployments", Action: "edit", Scope: authz.ScopeHandler})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/yaml/delete", authz.Policy{Resource: "deployments", Action: "delete", Scope: authz.ScopeHandler})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/events/:type/:ns/:name", authz.Policy{Resource: "events", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/clusters/:id/workloads/describe/:type/:ns/:name", authz.Policy{Resource: "deployments", Action: "view", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/clusters/:id/workloads/batch", authz.Policy{Resource: "operations", Action: "execute", Scope: authz.ScopeHandler})
	registry.MustRegister("GET", "/api/v1/clusters/:id/cost/config", authz.Policy{Resource: "cost", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/clusters/:id/cost/config", authz.Policy{Resource: "cost", Action: "edit", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/clusters/:id/cost/analysis", authz.Policy{Resource: "cost", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ops/:id/metrics/trend", authz.Policy{Resource: "metrics", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ops/:id/events/timeline", authz.Policy{Resource: "events", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ops/:id/nodes/pressure", authz.Policy{Resource: "nodes", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/ops/:id/rollback/deployment/:ns/:name", authz.Policy{Resource: "operations", Action: "execute", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/ops/:id/resource-graph", authz.Policy{Resource: "operations", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ops/:id/rbac", authz.Policy{Resource: "operations", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ops/:id/idle-resources", authz.Policy{Resource: "operations", Action: "view", Scope: authz.ScopeCluster})
	registry.MustRegister("POST", "/api/v1/ops/:id/idle-resources/clean", authz.Policy{Resource: "operations", Action: "execute", Scope: authz.ScopeHandler})
	registry.MustRegister("GET", "/api/v1/tenants", authz.Policy{Resource: "tenants", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/tenants", authz.Policy{Resource: "tenants", Action: "create", Scope: authz.ScopePlatform})
	registry.MustRegister("GET", "/api/v1/tenants/:id", authz.Policy{Resource: "tenants", Action: "view", Scope: authz.ScopePlatform})
	registry.MustRegister("PUT", "/api/v1/tenants/:id", authz.Policy{Resource: "tenants", Action: "edit", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/tenants/:id", authz.Policy{Resource: "tenants", Action: "delete", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/tenants/:id/members", authz.Policy{Resource: "tenants", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/tenants/:id/members/:userId", authz.Policy{Resource: "tenants", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/tenants/:id/namespaces", authz.Policy{Resource: "tenants", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("DELETE", "/api/v1/tenants/:id/namespaces/:nsId", authz.Policy{Resource: "tenants", Action: "admin", Scope: authz.ScopePlatform})
	registry.MustRegister("POST", "/api/v1/ws/tickets/pod/:id/:ns/:name", authz.Policy{Resource: "pods", Action: "exec", Scope: authz.ScopeNamespace})
	registry.MustRegister("POST", "/api/v1/ws/tickets/node/:id/:name", authz.Policy{Resource: "nodes", Action: "admin", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/ws/terminal/:id/:ns/:name", authz.Policy{Resource: "pods", Action: "exec", Scope: authz.ScopeNamespace})
	registry.MustRegister("GET", "/api/v1/ws/node-shell/:id/:name", authz.Policy{Resource: "nodes", Action: "admin", Scope: authz.ScopeCluster})
	registry.MustRegister("GET", "/api/v1/modules", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("GET", "/api/v1/modules/menus", authz.Policy{AuthenticatedOnly: true})
	registry.MustRegister("GET", "/api/v1/modules/:name", authz.Policy{AuthenticatedOnly: true})
}
